sudo: required
services: 
  - docker

before_install:
  - docker build -t dralan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dralan/react-test npm test

after_success:
  - docker build -t dralan/multi-client ./client
  - docker build -t dralan/multi-nginx ./nginx
  - docker build -t dralan/multi-server ./server
  - docker build -t dralan/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those and push to docker hub
  - docker push dralan/multi-client
  - docker push dralan/multi-nginx
  - docker push dralan/multi-server
  - docker push dralan/multi-worker